spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
mybatis:
  type-aliases-package: org.test.springTest.model
  mapper-locations: classpath:mapper/*.xml
